dataset:
  name: "VGGSound"
  hf_repo: "txya900619/vggsound-16k"
  split: "all"            # 사용할 데이터셋 split ("train" 또는 "test")
  cache_dir: "input"       # 전체 다운로드(streaming: false) 시 저장될 로컬 경로
  streaming: false         # true: 실시간 스트리밍(테스트) / false: 로컬 다운로드 후 매핑(실전용)
  samples_per_class: "all"

models:
  - name: "laion"
    type: "huggingface" # HF automated load
    hf_model_id: "laion/clap-htsat-unfused" 
    enabled: true
  - name: "mga"
    type: "local" # Cloned repo + local checkpoint
    repo_path: "models_third_party/MGA-CLAP"
    checkpoint_path: "checkpoints/mga-clap.pt"
    hf_download:
      repo_id: "wjm9765/clap_weights"
      repo_type: "dataset"
      filename: "mga-clap.pt"
    enabled: true
  - name: "msclap"
    type: "pypi"
    version: "2023"
    enabled: true
  - name: "m2d"
    type: "local"
    repo_path: "models_third_party/m2d"
    checkpoint_path: "checkpoints/checkpoint-30.pth"
    hf_download:
      repo_id: "wjm9765/clap_weights"
      repo_type: "dataset"
      filename: "checkpoint-30.pth"
    enabled: true

execution:
  batch_size: 16
  device: "cuda"
  output_dir: "results/eval_outputs"
  strategy: "sequential"
  use_accelerate: true

evaluation:
  results_dir: "results/eval_outputs"
  top_k_list: [1, 5, 10]

analysis:
  input_dir: "results/eval_outputs"
  output_dir: "analysis_output"
  cache_filename: "eval.jsonl"
  cmap: "RdBu"
  max_samples_per_category: 2000
  model_order: ["laion", "m2d", "mga", "msclap"]
  force_rebuild_cache: false
