[project]
name = "clap_eval"
version = "0.1.0"
description = "Evaluation Pipeline for CLAP Models (LAION, MGA, M2D)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "transformers",
    "accelerate",
    "pyyaml>=6.0",
    "tqdm",
    "pandas",
    "librosa",
    "numpy",
    "huggingface_hub",
    "datasets<4.0.0",
    "resampy",
    "timm",
    "einops",
    "nnAudio",
    "sentence_transformers",
    "ruamel.yaml",
    "torchlibrosa",
    "wandb",
    "loguru",
    "sed_scores_eval==0.0.0",
    "setuptools<70.0.0"
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" }
]
torchaudio = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" }
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/clap_eval"]
